const mongoose = require('mongoose')
const { User, Post } = require('../../data/models')
const updateUserPassword = require('./updateUserPassword')

mongoose.connect('mongodb://127.0.0.1:27017/data-project-test')
    .then(() => Promise.all([User.deleteMany(), Post.deleteMany()]))
    .then(() => User.create({ name: 'pepe.grillo', email: 'pepe@grillo.com', password: '123123123', avatar: 'http://www.image.com/avatar.jpg' }))
    .then(user => updateUserPassword(user.id, '123123123', '234234234', '234234234'))
    .then(console.log)
    .catch(console.error)
    .finally(() => mongoose.disconnect())